# Generated by Django 3.0.6 on 2020-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
