# Generated by Django 3.0.6 on 2020-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200602_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='favorite',
            field=models.ManyToManyField(to='recipe.RecipeItem'),
        ),
    ]
