# Generated by Django 3.0.6 on 2020-06-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipeitem_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='recipe.RecipeItem'),
        ),
    ]
