# Generated by Django 3.0.6 on 2020-06-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200603_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='favorite',
        ),
        migrations.AddField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to='recipe.RecipeItem'),
        ),
    ]
