# Generated by Django 3.0.6 on 2020-06-03 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200603_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
